#!/bin/sh -ex
BUILD=/rnsdhpc/code/build/curng
SOURCE=/rnsdhpc/code/src/curng

test -d "$BUILD" || mkdir -p "$BUILD"
cd $BUILD

cmake \
  -G Ninja \
  -D CURNG_USE_CUDA=OFF \
  -D BUILD_SHARED_LIBS=ON \
  -D CMAKE_CXX_FLAGS="-Wall -Wextra" \
  -D CMAKE_INSTALL_PREFIX="/rnsdhpc/code/install/curng" \
  $SOURCE
ninja
